seed: 7
save_dir: /home/tcastellani/projects/run

data:
  path: /project2/cdonnat/sleepstages/data/pt/non_overlapping_data.pt
  batch_size: 64
  num_workers: 4
  split: [0.6, 0.20, 0.20]
  augment:
    strategy: null
    proportion: null
  edge:
    tsh: null
    top: null

models:
  - name: mlp_baseline
    architecture: mlp
    params:
      input_dim: 347
      hidden_dims: [64, 64]
      num_classes: 4
      lr: 0.001
      wd: 0.001
      loss_type: weighted_cross_entropy
    trainer:
      max_epochs: 50
      accelerator: auto
      devices: 2
      log_every_n_steps: 10
