seed: 23
save_dir: /home/tcastellani/projects/neurograph_run

data:
  path: /project2/cdonnat/sleepstages/data/pt/non_overlapping_data.pt
  batch_size: 48
  num_workers: 4
  split: [0.7, 0.20, 0.10]
  augment:
    strategy: null
    proportion: null
  edge:
    tsh: null
    top: 0.05

models:
  - name: gnn_sage
    architecture: gnn
    params:
      input_dim: 347
      hidden_channels: 64
      num_layers: 3
      dropout: 0.5
      edge_dropout: 0.0          
      num_classes: 4
      mlp_hidden: [64, 32]
      lr: 0.001                 
      wd: 0.0001                 
      gnn_layer: SAGEConv
      pooling_fn: sort
      sort_pool_k: 10
      residual_connections: true 
      loss_type: weighted_cross_entropy
      conv1d_out: 128
      conv1d_kernel_size: 5
    trainer:
      max_epochs: 70            
      accelerator: auto
      devices: 1
      log_every_n_steps: 5

  - name: logistic_reg
    architecture: logistic
    params:
      input_dim: 347
      num_classes: 4
      lr: 5.0e-3
      loss_type: weighted_cross_entropy
    trainer:
      max_epochs: 40
      accelerator: auto
      devices: 1
  
  - name: mlp
    architecture: mlp
    params:
      input_dim: 347
      hidden_dims: [64, 64]
      dropout: 0.5
      num_classes: 4
      lr: 5.0e-3
      loss_type: weighted_cross_entropy
    trainer:
      max_epochs: 40
      accelerator: auto
      devices: 1