seed: 23
save_dir: /home/tcastellani/projects/geodesic_run

data:
  path: /project2/cdonnat/sleepstages/data/pt/non_overlapping_data.pt
  batch_size: 48
  num_workers: 4
  split: [0.6, 0.25, 0.15]
  augment:
    strategy: geodesic
    proportion: 0.4
  edge:
    tsh: 0.0
    top: null

models:
  - name: gnn_sage
    architecture: gnn
    params:
      input_dim: 347
      hidden_channels: 64
      num_layers: 3
      dropout: 0.5
      edge_dropout: 1          
      num_classes: 4
      mlp_hidden: [64, 32]
      lr: 0.0001                 
      wd: 0.001                 
      gnn_layer: SAGEConv
      pooling_fn: mean
      sort_pool_k: 10
      residual_connections: true 
      loss_type: cross_entropy
      conv1d_out: 128
      conv1d_kernel_size: 5
    trainer:
      max_epochs: 70            
      accelerator: auto
      devices: 1
      log_every_n_steps: 5