seed: 42
save_dir: neurograph_run

data:
  path: /project2/cdonnat/sleepstages/data/pt/non_overlapping_data.pt
  batch_size: 32
  num_workers: 4
  split: [0.6, 0.2, 0.2]
  augment:
    strategy: null
    proportion: null
  edge:
    tsh: null
    top: 0.10

models:
  - name: neurograph_experiment2
    architecture: neurograph
    params:
      hidden_channels: 64       
      hidden: 128               
      num_layers: 3             
      input_dim: 347
      gnn_layer: GCNConv     
      lr: 0.001
      wd: 0.001
      loss_type: weighted_cross_entropy
      num_classes: 4
    trainer:
      max_epochs: 50
      accelerator: auto
      devices: 1
      log_every_n_steps: 10 