seed: 7
save_dir: /home/tcastellani/projects/run

data:
  path: /home/tcastellani/projects/sleepstages/experiments/simulated_data/simulated_T100_snr010.pt
  batch_size: 32
  num_workers: 4
  split: [0.6, 0.3, 0.1]
  augment:
    strategy: null
    proportion: null

models:
  - name: C_simulated_T100_snr01
    architecture: logistic
    params:
      input_dim: 347
      num_classes: 4
      lr: 0.0001
      wd: 0.0001
      loss_type: weighted_cross_entropy
      self_conv: false
      self_conv_adj: false
      edge_top: null
      edge_tsh: null
      edge_weighted: false
    trainer:
      max_epochs: 50
      accelerator: auto
      devices: 2
      log_every_n_steps: 10
  - name: CC_simulated_T100_snr01
    architecture: logistic
    params:
      input_dim: 347
      num_classes: 4
      lr: 0.0001
      wd: 0.0001
      loss_type: weighted_cross_entropy
      self_conv: true
      self_conv_adj: false
      edge_top: null
      edge_tsh: null
      edge_weighted: false
    trainer:
      max_epochs: 50
      accelerator: auto
      devices: 2
      log_every_n_steps: 10
  - name: AC_simulated_T100_snr01
    architecture: logistic
    params:
      input_dim: 347
      num_classes: 4
      lr: 0.0001
      wd: 0.0001
      loss_type: weighted_cross_entropy
      self_conv: true
      self_conv_adj: true
      edge_top: 0.10
      edge_tsh: null
      edge_weighted: false
    trainer:
      max_epochs: 50
      accelerator: auto
      devices: 2
      log_every_n_steps: 10